[package]
name = "duck-mem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#duckdb = "0.3.2"
duckdb = {version = "0.3.2", features = ["bundled", "r2d2", "modern-full"]}
